CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

INSERT OR IGNORE INTO users (name) VALUES ('Bob');
INSERT OR IGNORE INTO users (name) VALUES ('Sally');
INSERT OR IGNORE INTO users (name) VALUES ('Sue');
INSERT OR IGNORE INTO users (name) VALUES ('Billy');

CREATE TABLE IF NOT EXISTS fbtable (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    match_start DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO fbtable (name) VALUES ('main');

CREATE TABLE IF NOT EXISTS match (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_length TEXT,
    table_id INTEGER NOT NULL,
    match_start DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    side TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS goal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    side TEXT NOT NULL,
    match_id INTEGER,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);
